
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[364] =
    {   0,
       59,   59,   63,   61,   60,   59,   38,   61,   61,   45,
       61,   61,   56,   57,   43,   41,   52,   42,   50,   44,
        6,    6,   53,   51,   34,   46,   35,   58,   58,   48,
       49,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   54,   61,   55,    0,    0,   60,   60,   59,
       33,    0,    0,   11,    0,    0,    0,   55,   36,    0,
        0,    0,    0,   39,   40,   47,    9,    0,    1,   10,
        5,    0,    6,    6,   49,   54,   48,   30,   32,   31,
       58,    0,    0,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   20,   58,   58,   58,   58,   58,   58,

       58,   37,   11,    0,    0,    1,    0,    7,    7,    0,
        0,    1,    0,    9,    0,    0,    0,    0,    1,    1,
        1,    9,    0,   10,    5,    0,    8,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   23,   17,   58,   58,
       58,   58,   58,   58,    0,    0,   11,    0,    0,    0,
        1,    1,    1,    1,    1,    0,    0,    0,    7,    0,
        0,    0,    1,    1,    1,    1,    1,    0,    9,    0,
        0,    2,    0,    1,    1,    1,    1,    1,    0,    9,
        0,   10,    8,   58,   25,   16,   58,   58,   58,   58,
       21,   58,   58,   58,   58,   58,   15,   58,   11,    0,

        0,    0,    2,    0,    1,    1,    1,    1,    1,    1,
        1,    0,    7,    0,    0,    0,    2,    0,    1,    1,
        1,    1,    1,    1,    1,    0,    2,    0,    0,    2,
        1,    1,    1,    1,    0,    9,   27,   12,   58,   58,
       58,   18,   58,   58,   58,   58,   22,    0,    2,    0,
        0,   11,    2,    0,    1,    1,    1,    1,    0,    0,
        2,    0,    0,    7,    2,    0,    1,    1,    1,    1,
        1,    1,   58,   58,   19,   58,   13,   29,   24,    1,
        1,    1,    1,    0,    1,    1,    1,    1,   58,   26,
       14,    0,   28,    0,    0,    0,    0,    4,    0,    0,

        0,    0,    0,    1,    0,    1,    3,    0,    4,    0,
        0,    1,    1,    1,    1,    0,    0,    0,    0,    1,
        1,    1,    1,    0,    2,    0,    1,    1,    1,    1,
        1,    1,    0,    2,    0,    1,    3,    1,    1,    1,
        1,    1,    0,    4,    2,    1,    1,    1,    1,    0,
        2,    0,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       26,   26,   26,   26,   26,   29,   26,   26,   26,   26,
       26,   26,   26,   26,   30,   26,   26,   26,   26,   26,
       31,   32,   33,    1,   26,    1,   34,   35,   36,   37,

       38,   39,   26,   40,   41,   26,   42,   43,   26,   44,
       45,   46,   26,   47,   48,   49,   50,   51,   52,   26,
       26,   26,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[399] =
    {   0,
        0,    0, 1012,  993,   54,   57,   44,   60,   46,   49,
       61,   66,  990,  983,  976,   57,  967,   64,   75,   68,
       82,  116,   65,  963,   89,   67,   90,  149,   67,  959,
      951,  915,   81,   58,  917,   61,   78,   69,  916,  901,
      900,  904,  923,   87,  919,  913,  105,  126,  135,  145,
      910,  199,  121,  909,  200,  137,  113,  906,  888,  201,
      132,  211,  147,  874,  869,  868,  226,  207,  138,  252,
      279,  220,  198,  313,  867,  866,  856,  851,  850,  849,
        0,  244,  205,  823,  807,  815,  809,  796,  798,  785,
      786,  785,  775,    0,  765,  754,  743,  713,  720,  718,

      717,  735, 1166,  747,  255,  271,  134,  729, 1166,  741,
      275,  302,  305,  717,  239,  718,  298,  323,  712,  332,
      145,  346,  339,  709,  319,  142,  352,  676,  663,  653,
      646,  631,  636,  633,  621,  620,    0,    0,  588,  592,
      572,  569,  571,  562,  380,  243,  364,  384,  393,  391,
      397,  574,  404,  415,  204,  208,  417,  250,  421,  428,
      440,  439,  336,  566,  441,  452,  310,  153,  448,  217,
      461,  334,  468,  472,  395,  475,  479,  486,  482,  560,
      162,  487,  557,  523,    0,    0,  507,  509,  499,  504,
        0,  478,  469,  454,  447,  444,    0,  431,  448,  504,

      289,  505,  506,  522,  526,  528,  539,  530,  550,  556,
      548,  268,  443,  554,  291,  567,  580,  584,  593,  597,
      610,  601,  614,  623,  627,  401, 1166,  631,  435,  634,
      635,  647,  648,  419,  638,  644,    0,    0,  396,  380,
      363,    0,  343,  342,  317,  304,    0,  661,  373,  672,
      663,  668,  685,  679,  693,  702,  706,  710,  408,  563,
      328,  719,  708,  723,  736,  730,  742,  753,  754,  766,
      762,  770,  277,  265,    0,  272,    0,    0,    0,  784,
      778,  786,  790,  445,  797,  806,  810,  808,  262,    0,
        0,  821,    0,  827,  370,  241,  573,  583,  671,  495,

      689,  829,  835,  764,  833,  839, 1166,  853,  857,  859,
      870,  603,  625,  876,  788,  877,  878,  894,  895,  496,
      896,  892,  875,  898,  799,  912,  920,  916,  929,  933,
      937,  946,  945,  943,  954,  962,  270,  953,  970,  971,
      973,  979,  987,  996, 1000, 1004, 1013, 1017, 1015, 1021,
     1024, 1035, 1037, 1038, 1041, 1039, 1055, 1064, 1066, 1062,
     1068, 1082, 1166,  266, 1107, 1109, 1111, 1113, 1115,  211,
     1117, 1119, 1121, 1123, 1125, 1127, 1129, 1131, 1133, 1135,
     1137, 1139, 1141, 1143, 1145, 1147,  208,  173, 1149,   87,
     1151,   64, 1153, 1155, 1157, 1159, 1161, 1163

    } ;

static const flex_int16_t yy_def[399] =
    {   0,
      363,    1,  363,  364,  364,  363,  364,  365,  364,  364,
      364,  366,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,   28,  364,
      364,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,  364,  364,  364,  364,  364,  364,  363,  363,
      364,  365,  367,  364,  365,  365,  364,  364,  364,  366,
      368,  366,  366,  364,  364,  364,  364,  369,  370,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
       28,  365,  366,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,  364,  363,  367,  371,  372,  364,  364,  363,  368,
      373,  374,  364,  364,  369,  375,  369,  369,  370,  376,
      370,  364,  364,  364,  364,  364,  364,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,  371,  377,  369,  371,  371,  371,
      372,  370,  378,  372,  372,  364,  373,  379,  369,  373,
      373,  373,  374,  370,  380,  374,  374,  364,  364,  375,
      369,  364,  381,  376,  370,  376,  376,  376,  364,  364,
      364,  364,  364,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,  375,  377,

      377,  371,  365,  382,  378,  372,  378,  376,  378,  378,
      378,  364,  375,  379,  379,  373,  366,  383,  380,  374,
      380,  376,  380,  380,  380,  375,  363,  369,  375,  369,
      384,  376,  376,  370,  364,  364,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,  377,  367,  371,
      377,  369,  371,  371,  385,  378,  378,  372,  364,  379,
      368,  373,  379,  369,  373,  373,  386,  380,  380,  374,
      376,  376,   28,   28,   28,   28,   28,   28,   28,  378,
      376,  378,  378,  364,  380,  376,  380,  380,   28,   28,
       28,  364,   28,  364,  387,  388,  387,  387,  387,  388,

      388,  388,  389,  390,  391,  392,  363,  389,  389,  389,
      389,  390,  390,  393,  390,  391,  391,  391,  391,  392,
      394,  392,  392,  389,  387,  395,  393,  390,  393,  393,
      393,  393,  391,  388,  396,  394,  375,  392,  394,  394,
      394,  394,  389,  389,  389,  397,  393,  393,  390,  391,
      391,  391,  398,  394,  394,  392,  393,  393,  393,  394,
      394,  394,    0,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363

    } ;

static const flex_int16_t yy_nxt[1222] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   29,   28,
       30,    4,   31,   28,   32,   33,   34,   35,   36,   28,
       37,   28,   28,   28,   28,   38,   39,   40,   28,   28,
       41,   42,   43,   44,   45,   48,   49,   48,   49,   50,
       49,   47,   53,   47,  320,   54,   47,   51,   61,   59,
       64,   47,   82,   58,   47,   46,   83,   55,   47,   65,
       68,   47,   47,   62,   47,   69,   57,  312,   66,   75,
       79,   56,   47,   67,   67,   89,   76,   63,   70,   47,

       71,   71,   90,   92,   47,   93,   47,   47,   72,   77,
       73,   73,   78,   80,   85,   96,   94,   68,   97,   72,
       86,   95,   69,   87,   73,   88,  103,   48,   49,   48,
       47,   73,   70,   47,   74,   74,   49,   49,   49,  363,
      102,  109,   72,   47,   73,   73,   49,   50,   49,  363,
      120,   47,  104,   72,   55,  121,  107,  120,   73,   47,
      127,  127,  121,  110,   62,   73,   47,   81,   81,  156,
       47,  169,  169,  300,   81,   81,   81,   81,   81,   47,
      182,  182,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,

       81,   53,   53,   61,   54,   54,  363,   61,  297,  116,
      108,  119,  105,   61,   46,   47,   55,  106,   62,  117,
      108,  206,   62,  111,  118,   47,   73,   73,  112,  226,
       56,   56,   63,  126,  227,  126,   63,   47,  127,  127,
       73,  116,   63,   47,   67,   67,   53,   73,  199,   54,
      212,  117,  113,  114,  114,  200,  118,  146,  301,  213,
      147,   55,  214,  113,  114,  302,   46,  148,  114,   47,
      122,  122,  149,   53,  201,   56,  152,  158,  123,  124,
      124,  215,  170,  153,  159,   47,  150,  160,  154,  123,
      124,  116,  161,  116,  124,   70,   47,   71,   71,  293,

      116,  200,  155,  214,   61,   72,  162,  125,  125,  291,
      171,  164,  363,  290,  165,  172,   72,  259,  168,  166,
      168,  125,   47,  169,  169,  116,  289,  220,  125,   70,
       47,   74,   74,  167,  116,  173,   47,  109,   61,   72,
      174,   73,   73,  279,  177,  164,   68,  125,  125,  178,
       72,   69,  181,  220,  181,   73,   47,  182,  182,  110,
      278,  125,   73,   47,  122,  122,  116,  167,  125,   47,
      127,  127,  179,  180,  180,  298,  117,  277,  103,  183,
      183,  118,  146,  179,  180,  147,  146,  299,  180,  147,
      183,  276,  148,  116,  183,  146,  202,  149,  147,   53,

      275,  203,  152,  148,  104,  204,  146,  120,  149,  208,
      205,  150,  121,  226,  206,  150,  209,   53,  363,  158,
      152,  210,  274,  116,  150,   47,  159,  153,  155,  160,
      158,  120,  154,  117,  161,  211,  121,  159,  118,  273,
      216,  116,  158,  158,  284,  217,  155,  170,  162,  159,
      222,  160,  218,  223,   61,  170,  161,  219,  224,  162,
      170,  164,   47,  116,  165,   47,  169,  169,  247,  166,
      229,  162,  225,  171,  116,  114,  114,  116,   47,  246,
      117,  116,  292,  167,  231,  230,  114,  177,  116,  232,
      114,  233,  178,  245,  244,  235,  234,  235,  231,   47,

      236,  236,  243,  232,   47,  182,  182,  146,   53,  199,
      147,   54,  301,  338,  124,  124,  248,  202,  105,  302,
      323,  249,   55,  106,  251,  124,  242,  252,  146,  124,
       53,  208,  116,  152,  148,  201,  150,   56,  255,  253,
      153,  146,  177,  256,  208,  154,  241,  178,  240,  239,
      116,  209,  146,  254,  238,  208,  210,  211,  146,  155,
      209,  208,  257,  213,  237,  210,  260,  258,  255,  158,
      211,  261,  213,  256,   47,  260,  159,   47,  298,  216,
       61,  211,   61,  175,   62,  215,  263,  211,  298,  108,
      299,  175,  111,  264,  215,  158,  160,  112,  162,   61,

      299,  265,  222,  116,  198,  267,  164,  197,  313,  165,
      268,   63,  158,  177,  166,  266,  158,  196,  178,  222,
      328,  195,  223,  222,  225,  158,  269,  224,  167,  116,
      313,  270,  222,  116,  194,  267,  116,  229,  193,  223,
      268,  225,  328,  117,  224,  225,  173,  177,  118,  116,
      116,  174,  272,  192,  225,   47,  236,  236,  191,  231,
      233,   47,  236,  236,  232,  175,  199,  190,  199,  189,
      116,  180,  180,  248,  146,  200,  298,  147,   53,  188,
      117,  116,  180,  303,  148,  118,  180,  146,  304,  149,
      147,  148,  201,  187,  201,  251,  149,  204,  281,  186,

      185,  305,  205,  150,  146,  209,  306,  208,  146,  184,
      282,  208,   53,  302,  255,  152,  150,  213,  257,  256,
      214,  158,  153,  206,  283,  116,   47,  154,  159,  175,
      170,  160,  116,  211,   47,  117,  161,  211,  158,  215,
      118,  155,  160,  363,  263,  159,   47,  161,  218,  363,
      162,  286,   47,  219,  223,  158,  158,  144,  143,  287,
      142,  141,  222,  222,  116,  267,  269,  162,   61,  313,
      268,  220,  116,  288,  177,  164,  314,  140,  165,  178,
      116,  315,  231,  166,  225,  225,  146,  232,  146,  208,
      177,  208,  116,  313,  139,  178,  209,  167,  255,  158,

      314,  210,  209,  256,  298,  315,  222,  210,  116,  223,
      116,  303,  158,  138,  224,  211,  304,  211,  177,  222,
      223,  137,  267,  178,  294,  224,  295,  268,  225,  136,
      294,  307,  295,  135,  134,  116,  133,  116,   47,  132,
      309,  225,  131,  296,   47,  317,  301,  310,  130,  296,
      318,  321,  311,  302,  129,  116,  322,  319,  309,  116,
      128,  116,  309,  323,  309,  310,   47,   47,   47,  310,
      311,  324,  116,   47,  311,  309,  325,  307,  116,  116,
      116,  330,  326,   47,   47,   47,   47,  327,  331,  317,
      333,   47,  338,  332,  318,  334,  116,  337,  116,  323,

      116,  319,  319,  309,  321,   47,  335,  317,  340,  322,
      324,  336,  318,  341,  229,  299,  323,  344,  319,  319,
      342,  313,  116,   47,  310,  330,   47,   47,  314,  345,
       47,  116,  346,  315,  330,  116,   47,  347,  330,  116,
       47,  331,  330,  101,  100,  331,  332,  116,  116,  348,
      332,  330,   99,   98,  349,  305,  229,  333,  346,   91,
      306,   84,  301,  347,  116,  321,  317,  302,   47,  319,
      322,  351,  116,  116,  353,  116,   47,  323,  352,  354,
       47,  337,  340,  355,   47,  353,  342,  341,  356,  116,
      354,  340,  309,   47,  342,  342,  341,  342,  116,  310,

       47,  309,  116,  342,  311,  309,  229,   47,  310,  358,
       47,  363,  326,  311,  363,  116,  331,  327,  330,  116,
      313,  359,  330,  116,  363,  346,  116,  314,  363,  348,
      347,  363,  315,  317,  328,  363,  335,  337,  318,  229,
      116,  336,  363,  116,  363,  319,  363,  317,  319,  340,
      353,  321,  318,  355,  361,  354,  322,  116,  338,  319,
      330,  362,  342,  323,  116,  342,  116,  331,  116,  330,
      116,  330,  332,  363,  340,  363,  331,  363,  346,  341,
      353,  332,  363,  347,  337,  354,  342,  363,  363,  363,
      363,  363,  342,  363,  340,  363,  363,  363,  363,  341,

      363,  363,  363,  363,  363,  363,  342,   52,   52,   60,
       60,   53,   53,   61,   61,  115,  115,  145,  145,  151,
      151,  157,  157,  163,  163,  116,  116,  176,  176,  146,
      146,  207,  207,  158,  158,  221,  221,  228,  228,  250,
      250,  262,  262,  271,  271,  280,  280,  285,  285,  308,
      308,  316,  316,  329,  329,  339,  339,  343,  343,  350,
      350,  357,  357,  360,  360,    3,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363
    } ;

static const flex_int16_t yy_chk[1222] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    7,    8,    9,  392,    8,   10,    7,   12,   11,
       16,    5,   29,   10,   16,   12,   29,    8,   11,   18,
       20,   18,   23,   12,   26,   20,    9,  390,   18,   23,
       26,    8,   19,   19,   19,   34,   25,   12,   21,   21,

       21,   21,   34,   36,   44,   36,   25,   27,   21,   25,
       21,   21,   25,   27,   33,   38,   37,   47,   38,   21,
       33,   37,   47,   33,   21,   33,   53,   48,   48,   48,
       57,   21,   22,   22,   22,   22,   49,   49,   49,   56,
       44,   61,   22,   48,   22,   22,   50,   50,   50,   63,
       69,  107,   53,   22,   56,   69,   57,  121,   22,  126,
      126,  126,  121,   61,   63,   22,   28,   28,   28,  107,
      168,  168,  168,  388,   28,   28,   28,   28,   28,  181,
      181,  181,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   52,   55,   60,   52,   55,  155,   83,  387,   68,
       60,  370,   55,   62,   83,   73,   52,   55,   60,   68,
       62,  155,   83,   62,   68,  156,   73,   73,   62,  170,
       52,   55,   60,   72,  170,   72,   83,   72,   72,   72,
       73,  115,   62,   67,   67,   67,   82,   73,  146,   82,
      156,  115,   67,   67,   67,  146,  115,  105,  296,  158,
      105,   82,  158,   67,   67,  296,  364,  105,   67,   70,
       70,   70,  105,  106,  146,   82,  106,  111,   70,   70,
       70,  158,  337,  106,  111,  212,  105,  111,  106,   70,
       70,  201,  111,  215,   70,   71,   71,   71,   71,  289,

      117,  201,  106,  215,  112,   71,  111,   71,   71,  276,
      117,  112,  167,  274,  112,  117,   71,  212,  113,  112,
      113,   71,  113,  113,  113,  118,  273,  167,   71,   74,
       74,   74,   74,  112,  120,  118,  125,  261,  163,   74,
      118,   74,   74,  246,  120,  163,  172,  125,  125,  120,
       74,  172,  123,  163,  123,   74,  123,  123,  123,  261,
      245,  125,   74,  122,  122,  122,  147,  163,  125,  127,
      127,  127,  122,  122,  122,  295,  147,  244,  249,  127,
      127,  147,  145,  122,  122,  145,  148,  295,  122,  148,
      127,  243,  145,  150,  127,  149,  148,  145,  149,  151,

      241,  148,  151,  150,  249,  149,  153,  175,  150,  153,
      149,  145,  175,  226,  151,  148,  153,  154,  226,  157,
      154,  153,  240,  159,  149,  259,  157,  154,  151,  157,
      160,  234,  154,  159,  157,  153,  234,  160,  159,  239,
      160,  162,  161,  165,  259,  160,  154,  229,  157,  161,
      165,  162,  161,  165,  166,  213,  162,  161,  165,  160,
      199,  166,  284,  171,  166,  169,  169,  169,  198,  166,
      173,  161,  165,  171,  174,  169,  169,  176,  171,  196,
      173,  177,  284,  166,  174,  173,  169,  176,  178,  174,
      169,  177,  176,  195,  194,  179,  177,  179,  178,  179,

      179,  179,  193,  178,  182,  182,  182,  202,  203,  200,
      202,  203,  300,  320,  182,  182,  200,  202,  203,  300,
      320,  200,  202,  203,  204,  182,  192,  204,  205,  182,
      206,  205,  208,  206,  204,  200,  202,  203,  205,  204,
      206,  207,  208,  205,  207,  206,  190,  208,  189,  188,
      211,  207,  209,  204,  187,  209,  207,  205,  210,  206,
      211,  210,  209,  214,  184,  211,  214,  209,  210,  216,
      207,  214,  260,  210,  183,  260,  216,  180,  297,  216,
      260,  209,  217,  164,  216,  214,  218,  210,  298,  217,
      297,  152,  217,  218,  260,  219,  218,  217,  216,  220,

      298,  218,  219,  222,  144,  219,  220,  143,  312,  220,
      219,  217,  221,  222,  220,  218,  223,  142,  222,  221,
      312,  141,  221,  223,  219,  224,  223,  221,  220,  225,
      313,  223,  224,  228,  140,  224,  230,  231,  139,  225,
      224,  221,  313,  228,  225,  223,  230,  231,  228,  232,
      233,  230,  231,  136,  224,  235,  235,  235,  135,  232,
      233,  236,  236,  236,  232,  233,  248,  134,  251,  133,
      252,  236,  236,  248,  250,  251,  299,  250,  248,  132,
      252,  254,  236,  299,  250,  252,  236,  253,  299,  250,
      253,  254,  248,  131,  251,  255,  254,  253,  255,  130,

      129,  301,  253,  250,  256,  255,  301,  256,  257,  128,
      255,  257,  258,  301,  256,  258,  253,  263,  257,  256,
      263,  262,  258,  257,  255,  264,  124,  258,  262,  119,
      116,  262,  266,  256,  114,  264,  262,  257,  265,  263,
      264,  258,  266,  110,  267,  265,  108,  266,  265,  104,
      262,  267,  102,  265,  267,  268,  269,  101,  100,  267,
       99,   98,  268,  269,  271,  268,  269,  265,  270,  304,
      268,  269,  272,  267,  271,  270,  304,   97,  270,  271,
      281,  304,  272,  270,  268,  269,  280,  272,  282,  280,
      281,  282,  283,  315,   96,  281,  280,  270,  282,  285,

      315,  280,  283,  282,  325,  315,  285,  283,  286,  285,
      288,  325,  287,   95,  285,  280,  325,  282,  286,  287,
      288,   93,  287,  286,  292,  288,  292,  287,  285,   92,
      294,  302,  294,   91,   90,  305,   89,  303,  292,   88,
      303,  287,   87,  292,  294,  305,  302,  303,   86,  294,
      305,  306,  303,  302,   85,  308,  306,  305,  308,  309,
       84,  310,  309,  306,  310,  308,   80,   79,   78,  309,
      308,  310,  311,   77,  309,  311,  310,  323,  314,  316,
      317,  314,  311,   76,   75,   66,   65,  311,  314,  316,
      317,   64,  323,  314,  316,  317,  318,  319,  321,  323,

      324,  316,  317,  324,  322,   59,  318,  319,  321,  322,
      324,  318,  319,  321,  326,  324,  322,  326,  318,  319,
      321,  328,  327,   58,  326,  327,   54,   51,  328,  326,
       46,  329,  327,  328,  329,  330,   45,  327,  330,  331,
       43,  329,  331,   42,   41,  330,  329,  333,  332,  331,
      330,  332,   40,   39,  331,  334,  335,  333,  332,   35,
      334,   32,  333,  332,  336,  338,  335,  334,   31,  333,
      338,  335,  339,  340,  336,  341,   30,  338,  335,  336,
       24,  342,  339,  340,   17,  341,  336,  339,  340,  343,
      341,  342,  343,   15,  339,  340,  342,  341,  344,  343,

       14,  344,  345,  342,  343,  345,  346,   13,  344,  346,
        4,    3,  345,  344,    0,  347,  346,  345,  347,  348,
      349,  346,  348,  350,    0,  347,  351,  349,    0,  348,
      347,    0,  349,  350,  348,    0,  351,  352,  350,  353,
      354,  351,    0,  355,    0,  350,    0,  352,  351,  353,
      354,  356,  352,  355,  353,  354,  356,  357,  355,  352,
      357,  353,  354,  356,  360,  355,  358,  357,  359,  358,
      361,  359,  357,    0,  360,    0,  358,    0,  359,  360,
      361,  358,    0,  359,  362,  361,  360,    0,    0,    0,
        0,    0,  361,    0,  362,    0,    0,    0,    0,  362,

        0,    0,    0,    0,    0,    0,  362,  365,  365,  366,
      366,  367,  367,  368,  368,  369,  369,  371,  371,  372,
      372,  373,  373,  374,  374,  375,  375,  376,  376,  377,
      377,  378,  378,  379,  379,  380,  380,  381,  381,  382,
      382,  383,  383,  384,  384,  385,  385,  386,  386,  389,
      389,  391,  391,  393,  393,  394,  394,  395,  395,  396,
      396,  397,  397,  398,  398,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[63] =
    {   0,
0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "patterns.l"
#line 2 "patterns.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	
	#include "y.tab.h"

	extern void yyerror(char *);
	void print_token();
	
#line 876 "lex.yy.c"
#line 877 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 23 "patterns.l"


#line 26 "patterns.l"
	/*	Headers and Libraries	*/
#line 1099 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 364 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1166 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "patterns.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 28 "patterns.l"
{;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 29 "patterns.l"
{printf("%s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "patterns.l"
{printf("%s\n", yytext);}
	YY_BREAK
/* Constants	*/
case 5:
YY_RULE_SETUP
#line 34 "patterns.l"
{ print_token(); yylval=atoi(yytext); return(T_CONSTANT); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "patterns.l"
{ print_token(); yylval=atoi(yytext); return(T_CONSTANT); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 36 "patterns.l"
{ print_token(); return(T_CONSTANT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "patterns.l"
{ print_token(); yylval=atof(yytext); return(T_CONSTANT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "patterns.l"
{ print_token(); yylval=atof(yytext); return(T_CONSTANT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "patterns.l"
{ print_token(); yylval=atof(yytext); return(T_CONSTANT); }
	YY_BREAK
/* String Literal	*/
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 43 "patterns.l"
{ print_token(); return(T_STRING_LITERAL); }
	YY_BREAK
/* Language Constructs	*/
/*"main"	{ print_token(); return (T_MAIN); }*/
case 12:
YY_RULE_SETUP
#line 48 "patterns.l"
{ print_token(); return(T_CLASS); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "patterns.l"
{ print_token(); return (T_PUBLIC); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "patterns.l"
{ print_token(); return (T_PRIVATE); }
	YY_BREAK
/*"using"	{ print_token(); return (T_USING); }*/
/*"namespace"	{ print_token(); return (T_NAMESPACE); }*/
/*"std"		{ print_token(); return (T_STD); }*/
/*"print"	{ print_token(); return (T_PRINT); }*/
/*"cout"	{ print_token(); return (T_COUT); }*/
/*"endl"	{ print_token(); return (T_ENDL); }*/
/*	Data Types	*/
case 15:
YY_RULE_SETUP
#line 60 "patterns.l"
{ print_token(); return (T_VOID); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "patterns.l"
{ print_token(); return (T_CHAR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "patterns.l"
{ print_token(); return (T_INT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "patterns.l"
{ print_token(); return (T_FLOAT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "patterns.l"
{ print_token(); return (T_DOUBLE); }
	YY_BREAK
/*	Control Structures */	
case 20:
YY_RULE_SETUP
#line 69 "patterns.l"
{ print_token(); return (T_IF); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "patterns.l"
{ print_token(); return (T_ELSE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "patterns.l"
{ print_token(); return (T_WHILE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "patterns.l"
{ print_token(); return (T_FOR); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "patterns.l"
{ print_token(); return (T_SWITCH); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "patterns.l"
{ print_token(); return (T_CASE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "patterns.l"
{ print_token(); return (T_DEFAULT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "patterns.l"
{ print_token(); return (T_BREAK); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "patterns.l"
{ print_token(); return (T_CONTINUE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "patterns.l"
{ print_token(); return (T_RETURN); }
	YY_BREAK
/*	Assignmet Operators	*/
/*
"+="	{ print_token(); return (T_ADD_ASGN); }
"-="	{ print_token(); return (T_SUB_ASGN); }
"*="	{ print_token(); return (T_MUL_ASGN); }
"/="	{ print_token(); return (T_DIV_ASGN); }
"%="	{ print_token(); return (T_MOD_ASGN); }
	*/
/*	Relational Operators	*/
case 30:
YY_RULE_SETUP
#line 92 "patterns.l"
{ print_token(); return (T_LE_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "patterns.l"
{ print_token(); return (T_GE_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "patterns.l"
{ print_token(); return (T_EQ_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "patterns.l"
{ print_token(); return (T_NE_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "patterns.l"
{ print_token(); return ('<'); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "patterns.l"
{ print_token(); return ('>');	}
	YY_BREAK
/*	Logical Operators	*/
case 36:
YY_RULE_SETUP
#line 100 "patterns.l"
{ print_token(); return (T_AND_OP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "patterns.l"
{ print_token(); return (T_OR_OP); }	
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "patterns.l"
{ print_token(); return ('!'); }
	YY_BREAK
/*	Arithmetic Operators	*/
case 39:
YY_RULE_SETUP
#line 106 "patterns.l"
{ print_token(); return (T_INC_OP); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "patterns.l"
{ print_token(); return (T_DEC_OP); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 109 "patterns.l"
{ print_token(); return ('+'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 110 "patterns.l"
{ print_token(); return ('-'); }	
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 111 "patterns.l"
{ print_token(); return ('*'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 "patterns.l"
{ print_token(); return ('/'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 "patterns.l"
{ print_token(); return ('%'); }
	YY_BREAK
/*	Synatx	*/
case 46:
YY_RULE_SETUP
#line 117 "patterns.l"
{ print_token(); return ('='); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "patterns.l"
{ print_token(); return (T_PTR_OP); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "patterns.l"
{ print_token(); return ('['); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "patterns.l"
{ print_token(); return (']'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 121 "patterns.l"
{ print_token(); return ('.'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 122 "patterns.l"
{ print_token(); return (';'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 123 "patterns.l"
{ print_token(); return (','); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 124 "patterns.l"
{ print_token(); return (':'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 125 "patterns.l"
{ printf("\n{\t"); return ('{'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 126 "patterns.l"
{ printf("\t}\n"); return ('}'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 127 "patterns.l"
{ print_token(); return ('('); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 128 "patterns.l"
{ print_token(); return (')'); }
	YY_BREAK
/*
"&"		{ print_token(); return('&'); }
"~"		{ print_token(); return('~'); }
"^"		{ print_token(); return('^'); }
"|"		{ print_token(); return('|'); }
"?"		{ print_token(); return('?'); }
	*/
case 58:
YY_RULE_SETUP
#line 137 "patterns.l"
{ print_token(); return(T_IDENTIFIER);}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 138 "patterns.l"
{ printf("\n");}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 139 "patterns.l"
{ printf(" "); }
	YY_BREAK
/*	Other	*/
case 61:
YY_RULE_SETUP
#line 142 "patterns.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 144 "patterns.l"
ECHO;
	YY_BREAK
#line 1514 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 364 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 364 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 363);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 144 "patterns.l"


void print_token()
{
	ECHO;
}

int yywrap(void)
{
	return 1;
}

