
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[366] =
    {   0,
       64,   64,   68,   66,   65,   64,   38,   66,   66,   45,
       58,   66,   56,   57,   43,   41,   52,   42,   50,   44,
        6,    6,   53,   51,   34,   46,   35,   62,   63,   63,
       48,   49,   60,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   54,   61,   55,   59,    0,    0,
       65,   64,   33,    0,    0,   11,    0,    0,    0,   55,
       36,    0,    0,    0,    0,   39,   40,   47,    9,    0,
        1,   10,    5,    0,    6,    6,   49,   54,   48,   30,
       32,   31,   63,    0,    0,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   20,   63,   63,   63,   63,

       63,   63,   63,   37,   11,    0,    0,    1,    0,    7,
        7,    0,    0,    1,    0,    9,    0,    0,    0,    0,
        1,    1,    1,    9,    0,   10,    5,    0,    8,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   23,   17,
       63,   63,   63,   63,   63,   63,    0,    0,   11,    0,
        0,    0,    1,    1,    1,    1,    1,    0,    0,    0,
        7,    0,    0,    0,    1,    1,    1,    1,    1,    0,
        9,    0,    0,    2,    0,    1,    1,    1,    1,    1,
        0,    9,    0,   10,    8,   63,   25,   16,   63,   63,
       63,   63,   21,   63,   63,   63,   63,   63,   15,   63,

       11,    0,    0,    0,    2,    0,    1,    1,    1,    1,
        1,    1,    1,    0,    7,    0,    0,    0,    2,    0,
        1,    1,    1,    1,    1,    1,    1,    0,    2,    0,
        0,    2,    1,    1,    1,    1,    0,    9,   27,   12,
       63,   63,   63,   18,   63,   63,   63,   63,   22,    0,
        2,    0,    0,   11,    2,    0,    1,    1,    1,    1,
        0,    0,    2,    0,    0,    7,    2,    0,    1,    1,
        1,    1,    1,    1,   63,   63,   19,   63,   13,   29,
       24,    1,    1,    1,    1,    0,    1,    1,    1,    1,
       63,   26,   14,    0,   28,    0,    0,    0,    0,    4,

        0,    0,    0,    0,    0,    1,    0,    1,    3,    0,
        4,    0,    0,    1,    1,    1,    1,    0,    0,    0,
        0,    1,    1,    1,    1,    0,    2,    0,    1,    1,
        1,    1,    1,    1,    0,    2,    0,    1,    3,    1,
        1,    1,    1,    1,    0,    4,    2,    1,    1,    1,
        1,    0,    2,    0,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       27,   27,   27,   27,   27,   30,   27,   27,   27,   27,
       27,   27,   27,   27,   31,   27,   27,   27,   27,   27,
       32,   33,   34,   35,   27,    1,   36,   37,   38,   39,

       40,   41,   27,   42,   43,   27,   44,   45,   27,   46,
       47,   48,   27,   49,   50,   51,   52,   53,   54,   27,
       27,   27,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[401] =
    {   0,
        0,    0,  978,  953,   57,  967,   42,   59,   45,   46,
       58,   69,  945,  936,  935,   55,  932,   64,   65,   68,
       86,  122,   72,  928,   91,   50,   76,  922,  157,   85,
      919,  918,  891,  855,   77,   61,  858,   51,   77,   58,
      862,  842,  848,  847,  870,   93,  863,  854,  853,  107,
      125,  863,  847,  127,  115,  846,  148,   75,  110,  836,
      829,  209,  122,  210,  141,  828,  825,  822,  226,  155,
      151,  254,  283,  215,  206,  319,  814,  806,  795,  791,
      788,  787,    0,  235,  229,  762,  744,  753,  750,  737,
      736,  722,  718,  719,  716,    0,  711,  718,  716,  699,

      704,  703,  696,  715, 1168,  728,  246,  257,  119,  712,
     1168,  721,  275,  294,  301,  704,  212,  705,  273,  274,
      697,  313,  152,  354,  326,  696,  323,  116,  347,  675,
      667,  649,  641,  633,  640,  635,  623,  626,    0,    0,
      605,  612,  594,  594,  592,  579,  345,  292,  367,  383,
      384,  390,  401,  600,  407,  408,  160,  171,  419,  296,
      415,  432,  433,  435,  247,  598,  444,  446,  278,  172,
      451,  204,  455,  208,  469,  471,  339,  472,  473,  475,
      481,  591,  314,  484,  587,  548,    0,    0,  540,  543,
      531,  537,    0,  515,  528,  520,  512,  497,    0,  488,

      507,  499,  169,  503,  505,  521,  527,  538,  540,  534,
      556,  562,  554,  128,  494,  566,  366,  575,  584,  588,
      597,  601,  610,  609,  622,  623,  626,  342, 1168,  634,
      481,  635,  646,  647,  648,  343,  530,  649,    0,    0,
      415,  410,  399,    0,  373,  377,  360,  339,    0,  664,
      394,  668,  509,  670,  686,  682,  690,  699,  703,  707,
      222,  716,  434,  725,  450,  724,  738,  741,  742,  754,
      760,  766,  777,  778,  310,  292,    0,  284,    0,    0,
        0,  779,  785,  798,  797,  391,  804,  805,  816,  817,
      249,    0,    0,  821,    0,  832,  165,  373,  304,  312,

      513,  387,  662,  552,  839,  815,  838,  835, 1168,  855,
      856,  864,  872,  492,  636,  873,  874,  880,  881,  894,
      897,  405,  898,  895,  578,  911,  912,  925,  929,  921,
      938,  942,  946,  955,  954,  908,  962,  963,  256,  964,
      980,  981,  982,  983, 1006, 1007, 1008, 1024, 1025, 1026,
      956, 1032, 1033, 1046, 1049, 1050, 1052,  979, 1063, 1076,
     1077, 1075, 1083, 1084, 1168,  247, 1109, 1111, 1113, 1115,
     1117,  217, 1119, 1121, 1123, 1125, 1127, 1129, 1131, 1133,
     1135, 1137, 1139, 1141, 1143, 1145, 1147, 1149,  213,  178,
     1151,  146, 1153,   69, 1155, 1157, 1159, 1161, 1163, 1165

    } ;

static const flex_int16_t yy_def[401] =
    {   0,
      365,    1,  365,  366,  366,  365,  366,  367,  366,  366,
      366,  368,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,   29,
      366,  366,  366,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,  366,  366,  366,  366,  366,  366,
      366,  365,  366,  367,  369,  366,  367,  367,  366,  366,
      366,  368,  370,  368,  368,  366,  366,  366,  366,  371,
      372,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,   29,  367,  368,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,  366,  365,  369,  373,  374,  366,  366,
      365,  370,  375,  376,  366,  366,  371,  377,  371,  371,
      372,  378,  372,  366,  366,  366,  366,  366,  366,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,  373,  379,  371,  373,
      373,  373,  374,  372,  380,  374,  374,  366,  375,  381,
      371,  375,  375,  375,  376,  372,  382,  376,  376,  366,
      366,  377,  371,  366,  383,  378,  372,  378,  378,  378,
      366,  366,  366,  366,  366,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

      377,  379,  379,  373,  367,  384,  380,  374,  380,  378,
      380,  380,  380,  366,  377,  381,  381,  375,  368,  385,
      382,  376,  382,  378,  382,  382,  382,  377,  365,  371,
      377,  371,  386,  378,  378,  372,  366,  366,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  379,
      369,  373,  379,  371,  373,  373,  387,  380,  380,  374,
      366,  381,  370,  375,  381,  371,  375,  375,  388,  382,
      382,  376,  378,  378,   29,   29,   29,   29,   29,   29,
       29,  380,  378,  380,  380,  366,  382,  378,  382,  382,
       29,   29,   29,  366,   29,  366,  389,  390,  389,  389,

      389,  390,  390,  390,  391,  392,  393,  394,  365,  391,
      391,  391,  391,  392,  392,  395,  392,  393,  393,  393,
      393,  394,  396,  394,  394,  391,  389,  397,  395,  392,
      395,  395,  395,  395,  393,  390,  398,  396,  377,  394,
      396,  396,  396,  396,  391,  391,  391,  399,  395,  395,
      392,  393,  393,  393,  400,  396,  396,  394,  395,  395,
      395,  396,  396,  396,    0,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365

    } ;

static const flex_int16_t yy_nxt[1227] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   30,
       29,   31,    4,   32,   33,   29,   34,   35,   36,   37,
       38,   29,   39,   29,   29,   29,   29,   40,   41,   42,
       29,   29,   43,   44,   45,   46,   47,   48,   51,   50,
       51,   55,   50,   50,   56,   53,   61,   50,   66,  322,
       60,   63,   50,   81,   50,   50,   57,  365,   49,   67,
       70,   50,   50,   69,   69,   71,   64,   59,   68,   50,
       84,   58,   57,   50,   85,   94,   77,   95,   78,   82,

       91,   65,   72,   50,   73,   73,   98,   92,   50,   99,
       50,   79,   87,   74,   80,   75,   75,   96,   88,   70,
      105,   89,   97,   90,   71,   74,   51,   50,   51,   55,
       75,  111,   56,   50,  129,  129,   50,   75,   72,   50,
       76,   76,   50,  365,   57,   50,  314,  106,  104,   74,
       55,   75,   75,   56,  112,  109,  158,  118,   64,   58,
      107,   74,  365,  122,  122,  108,   75,  119,  123,  123,
      300,  118,  120,   75,   50,   83,   83,  208,  302,  261,
       58,  202,  301,   83,   83,   83,   83,   83,   50,   50,
      171,  171,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   63,   63,  299,  118,  214,  228,  121,  110,  110,
       70,  229,  113,   50,  119,   71,   64,  114,  128,  120,
      128,   63,   50,  129,  129,   75,   75,   55,   49,   50,
       56,   65,   65,   50,   69,   69,   64,   49,  148,   63,
       75,  149,   57,  115,  116,  116,  166,   75,  150,   55,
      286,   65,  154,  151,  222,  115,  116,   58,  172,  155,
      116,   50,  124,  124,  156,  118,  118,  160,  152,  169,
      365,  125,  126,  126,  161,  173,  175,  162,  295,  157,
      174,  176,  163,  125,  126,  222,   63,  201,  126,   72,

       50,   73,   73,  166,  202,  215,  167,  164,  216,  300,
       74,  168,  127,  127,  170,  118,  170,  300,   50,  171,
      171,  301,   74,  293,  203,  179,  169,  127,  217,  301,
      180,   50,  184,  184,  127,   72,   50,   76,   76,  183,
       50,  183,  292,   50,  184,  184,   74,  148,   75,   75,
      149,  122,  127,  127,  228,  122,  123,  150,   74,  365,
      123,  291,  151,   75,   50,  129,  129,  127,  118,  118,
       75,   50,  124,  124,  127,  185,  185,  152,  216,  119,
      281,  181,  182,  182,  120,  148,  148,  185,  149,  149,
      303,  185,  118,  181,  182,  204,  206,  304,  182,  105,

      205,  207,  150,   55,  303,  280,  154,  151,   50,  148,
       55,  304,  210,  154,  279,  152,  152,  118,  208,  211,
      155,  160,  340,  278,  212,  156,  106,  119,  161,  325,
      294,  162,  120,  157,  160,  160,  163,  118,  277,  213,
      157,  161,  161,  111,  218,  220,  160,  162,   63,  219,
      221,  164,  163,  224,  276,  166,  225,  118,  167,  215,
      275,  226,  216,  168,  164,  164,  112,  173,   50,  171,
      171,  231,   50,  118,  118,  118,  227,  118,  169,  116,
      116,  119,  217,  233,  179,  235,  232,  233,  234,  180,
      236,  116,  234,  172,  237,  116,  237,  315,   50,  238,

      238,   50,  184,  184,  201,  148,  172,   55,  149,  330,
       56,  250,  126,  126,  201,  204,  251,  107,  300,  172,
       57,  202,  108,  253,  126,  305,  254,  249,  126,  148,
      306,  203,  210,  150,  248,  152,  118,   58,  255,  257,
       55,  203,  148,  154,  258,  210,  179,   50,  238,  238,
      155,  180,  211,  256,  309,  156,  118,  212,  148,  213,
      247,  210,  246,  245,  148,  244,  211,  210,  259,  303,
      157,  212,  213,  260,  257,  215,  304,  160,  262,  258,
      309,  243,  242,  263,  161,  241,   63,  218,  213,  240,
      265,  239,   64,  110,  213,  340,  113,  266,  217,  160,

      162,  114,  325,   63,   50,  267,  224,  164,   50,  269,
      166,  118,  160,  167,  270,  177,   65,  177,  168,  224,
      268,  179,  225,  200,  160,  160,  180,  226,  118,  227,
      199,  224,  224,  169,  271,  269,  118,  118,  225,  272,
      270,  315,  227,  226,  198,  197,  119,  175,  231,  118,
      118,  120,  176,  330,  227,  227,  196,  195,  179,  233,
      235,  194,  193,  274,  234,  177,   50,  238,  238,  201,
      148,  192,  118,  149,  307,  191,  250,  182,  182,  308,
      150,   55,  119,  190,  118,  151,  304,  120,  148,  182,
      189,  149,  253,  182,  150,  283,  203,  188,  206,  151,

      152,  148,  211,  207,  210,  148,  187,  284,  210,   55,
      186,  257,  154,   50,  177,  259,  258,  172,  152,  155,
      208,   50,  285,  365,  156,  215,  118,  160,  262,   50,
      365,  213,   50,   63,  161,  213,  119,  162,  146,  157,
      160,  120,  163,  118,  265,  145,  144,  161,  217,  143,
      220,  288,  142,  162,  225,  221,  160,  164,  163,  289,
      141,  140,  160,  224,  139,  138,  269,  137,   63,  224,
      164,  270,  271,  136,  290,  166,  135,  222,  167,  118,
      118,  148,  134,  168,  210,  133,  227,  118,  132,  179,
      233,  211,  227,  131,  180,  234,  212,  179,  169,  118,

      148,  130,  180,  210,   50,   50,  160,  118,   50,  211,
      257,  213,   50,  224,  212,  258,  225,  179,  160,  118,
      315,  226,  180,   50,  296,  224,  297,  316,  269,  225,
      213,   50,  317,  270,  226,  296,  227,  297,   50,   50,
      118,  118,   50,  298,  311,   50,   50,  323,  227,   50,
      319,  312,  324,   50,  298,  320,  313,  118,  118,  325,
      311,  311,  321,   50,   50,   52,  118,  312,  312,  311,
       50,   50,  313,  313,  118,  118,  326,  311,  332,  315,
       50,  327,  118,  118,  328,  333,  316,   50,  103,  329,
      334,  317,  319,  335,  102,  101,  118,  320,  336,  339,

      118,  100,   93,   86,  321,  321,  337,  323,   50,  319,
      342,  338,  324,  118,  320,  343,  311,  300,  321,  325,
      307,  321,  344,  326,  305,  308,  315,  231,  301,  306,
      346,  118,  304,  316,  332,   50,   50,  312,  317,   50,
      118,  348,  347,  332,  118,   50,  349,  332,  118,   50,
      333,  332,   50,   50,  333,  334,  118,  118,  350,  334,
      332,  315,   50,  351,  231,  118,  335,  348,  316,   52,
       50,  303,  349,  317,  319,  355,  323,  365,  321,  353,
      356,  324,  118,  118,  118,  339,  354,  344,  325,  365,
      365,  323,  342,  357,  355,  342,  324,  343,  358,  356,

      343,  365,  365,  325,  344,  344,  344,  344,  118,  118,
      118,  311,  311,  311,  365,  365,  365,  365,  312,  312,
      328,  365,  365,  313,  313,  329,  231,  118,  118,  360,
      332,  332,  365,  365,  118,  118,  333,  348,  350,  365,
      365,  361,  349,  330,  319,  337,  365,  365,  339,  320,
      338,  231,  118,  365,  118,  365,  321,  321,  319,  365,
      365,  342,  355,  320,  357,  118,  363,  356,  332,  340,
      321,  365,  365,  364,  344,  333,  344,  118,  118,  118,
      334,  332,  332,  365,  365,  118,  339,  342,  333,  348,
      365,  365,  343,  334,  349,  355,  342,  365,  365,  344,

      356,  343,  365,  365,  365,  365,  365,  344,  344,   54,
       54,   62,   62,   55,   55,   63,   63,  117,  117,  147,
      147,  153,  153,  159,  159,  165,  165,  118,  118,  178,
      178,  148,  148,  209,  209,  160,  160,  223,  223,  230,
      230,  252,  252,  264,  264,  273,  273,  282,  282,  287,
      287,  310,  310,  318,  318,  331,  331,  341,  341,  345,
      345,  352,  352,  359,  359,  362,  362,    3,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365
    } ;

static const flex_int16_t yy_chk[1227] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    7,
        5,    8,    9,   10,    8,    7,   11,   26,   16,  394,
       10,   12,   16,   26,    5,   11,    8,   58,   12,   18,
       20,   18,   19,   19,   19,   20,   12,    9,   18,   23,
       30,    8,   58,   27,   30,   38,   23,   38,   25,   27,

       36,   12,   21,   21,   21,   21,   40,   36,   25,   40,
       46,   25,   35,   21,   25,   21,   21,   39,   35,   50,
       55,   35,   39,   35,   50,   21,   51,   59,   51,   54,
       21,   63,   54,  128,  128,  128,  109,   21,   22,   22,
       22,   22,   51,   65,   54,  214,  392,   55,   46,   22,
       57,   22,   22,   57,   63,   59,  109,   70,   65,   54,
       57,   22,  157,   71,  123,   57,   22,   70,   71,  123,
      297,  203,   70,   22,   29,   29,   29,  157,  390,  214,
       57,  203,  297,   29,   29,   29,   29,   29,  158,  170,
      170,  170,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   62,   64,  389,  117,  158,  172,  372,   62,   64,
      174,  172,   64,   75,  117,  174,   62,   64,   74,  117,
       74,   85,   74,   74,   74,   75,   75,   84,   85,  261,
       84,   62,   64,   69,   69,   69,   85,  366,  107,  165,
       75,  107,   84,   69,   69,   69,  165,   75,  107,  108,
      261,   85,  108,  107,  165,   69,   69,   84,  339,  108,
       69,   72,   72,   72,  108,  119,  120,  113,  107,  165,
      169,   72,   72,   72,  113,  119,  120,  113,  291,  108,
      119,  120,  113,   72,   72,  169,  114,  148,   72,   73,

       73,   73,   73,  114,  148,  160,  114,  113,  160,  299,
       73,  114,   73,   73,  115,  122,  115,  300,  115,  115,
      115,  299,   73,  278,  148,  122,  114,   73,  160,  300,
      122,  183,  183,  183,   73,   76,   76,   76,   76,  125,
      127,  125,  276,  125,  125,  125,   76,  147,   76,   76,
      147,  177,  127,  127,  228,  236,  177,  147,   76,  228,
      236,  275,  147,   76,  129,  129,  129,  127,  217,  149,
       76,  124,  124,  124,  127,  129,  129,  147,  217,  149,
      248,  124,  124,  124,  149,  150,  151,  129,  150,  151,
      298,  129,  152,  124,  124,  150,  151,  298,  124,  251,

      150,  151,  152,  153,  302,  247,  153,  152,  286,  155,
      156,  302,  155,  156,  246,  150,  151,  161,  153,  155,
      156,  159,  322,  245,  155,  156,  251,  161,  159,  322,
      286,  159,  161,  153,  162,  163,  159,  164,  243,  155,
      156,  162,  163,  263,  162,  163,  167,  164,  168,  162,
      163,  159,  164,  167,  242,  168,  167,  173,  168,  265,
      241,  167,  265,  168,  162,  163,  263,  173,  171,  171,
      171,  175,  173,  176,  178,  179,  167,  180,  168,  171,
      171,  175,  265,  176,  178,  179,  175,  180,  176,  178,
      179,  171,  180,  231,  181,  171,  181,  314,  181,  181,

      181,  184,  184,  184,  202,  204,  215,  205,  204,  314,
      205,  202,  184,  184,  253,  204,  202,  205,  301,  201,
      204,  253,  205,  206,  184,  301,  206,  200,  184,  207,
      301,  202,  207,  206,  198,  204,  210,  205,  206,  207,
      208,  253,  209,  208,  207,  209,  210,  237,  237,  237,
      208,  210,  209,  206,  304,  208,  213,  209,  211,  207,
      197,  211,  196,  195,  212,  194,  213,  212,  211,  304,
      208,  213,  209,  211,  212,  216,  304,  218,  216,  212,
      325,  192,  191,  216,  218,  190,  219,  218,  211,  189,
      220,  186,  218,  219,  212,  325,  219,  220,  216,  221,

      220,  219,  325,  222,  185,  220,  221,  218,  182,  221,
      222,  224,  223,  222,  221,  166,  219,  154,  222,  223,
      220,  224,  223,  146,  225,  226,  224,  223,  227,  221,
      145,  225,  226,  222,  225,  226,  230,  232,  227,  225,
      226,  315,  223,  227,  144,  143,  230,  232,  233,  234,
      235,  230,  232,  315,  225,  226,  142,  141,  233,  234,
      235,  138,  137,  233,  234,  235,  238,  238,  238,  250,
      252,  136,  254,  252,  303,  135,  250,  238,  238,  303,
      252,  250,  254,  134,  256,  252,  303,  254,  255,  238,
      133,  255,  257,  238,  256,  257,  250,  132,  255,  256,

      252,  258,  257,  255,  258,  259,  131,  257,  259,  260,
      130,  258,  260,  126,  121,  259,  258,  118,  255,  260,
      259,  116,  257,  112,  260,  262,  266,  264,  262,  110,
      106,  258,  104,  262,  264,  259,  266,  264,  103,  260,
      267,  266,  264,  268,  269,  102,  101,  267,  262,  100,
      267,  269,   99,  268,  269,  267,  270,  264,  268,  269,
       98,   97,  271,  270,   95,   94,  270,   93,  272,  271,
      267,  270,  271,   92,  269,  272,   91,  271,  272,  273,
      274,  282,   90,  272,  282,   89,  270,  283,   88,  273,
      274,  282,  271,   87,  273,  274,  282,  283,  272,  285,

      284,   86,  283,  284,   82,   81,  287,  288,   80,  285,
      284,  282,   79,  287,  285,  284,  287,  288,  289,  290,
      306,  287,  288,   78,  294,  289,  294,  306,  289,  290,
      284,   77,  306,  289,  290,  296,  287,  296,  294,   68,
      307,  305,   67,  294,  305,   66,   61,  308,  289,  296,
      307,  305,  308,   60,  296,  307,  305,  310,  311,  308,
      310,  311,  307,   56,   53,   52,  312,  310,  311,  312,
       49,   48,  310,  311,  313,  316,  312,  313,  316,  317,
       47,  312,  318,  319,  313,  316,  317,   45,   44,  313,
      316,  317,  318,  319,   43,   42,  320,  318,  319,  321,

      323,   41,   37,   34,  318,  319,  320,  324,   33,  321,
      323,  320,  324,  326,  321,  323,  326,  327,  320,  324,
      336,  321,  323,  326,  327,  336,  330,  328,  326,  327,
      328,  329,  336,  330,  329,   32,   31,  328,  330,   28,
      331,  329,  328,  331,  332,   24,  329,  332,  333,   17,
      331,  333,   15,   14,  332,  331,  335,  334,  333,  332,
      334,  351,   13,  333,  337,  338,  335,  334,  351,    6,
        4,  335,  334,  351,  337,  338,  340,    3,  335,  337,
      338,  340,  341,  342,  343,  344,  337,  338,  340,    0,
        0,  358,  341,  342,  343,  344,  358,  341,  342,  343,

      344,    0,    0,  358,  341,  342,  343,  344,  345,  346,
      347,  345,  346,  347,    0,    0,    0,    0,  345,  346,
      347,    0,    0,  345,  346,  347,  348,  349,  350,  348,
      349,  350,    0,    0,  352,  353,  348,  349,  350,    0,
        0,  348,  349,  350,  352,  353,    0,    0,  354,  352,
      353,  355,  356,    0,  357,    0,  352,  353,  354,    0,
        0,  355,  356,  354,  357,  359,  355,  356,  359,  357,
      354,    0,    0,  355,  356,  359,  357,  362,  360,  361,
      359,  360,  361,    0,    0,  363,  364,  362,  360,  361,
        0,    0,  362,  360,  361,  363,  364,    0,    0,  362,

      363,  364,    0,    0,    0,    0,    0,  363,  364,  367,
      367,  368,  368,  369,  369,  370,  370,  371,  371,  373,
      373,  374,  374,  375,  375,  376,  376,  377,  377,  378,
      378,  379,  379,  380,  380,  381,  381,  382,  382,  383,
      383,  384,  384,  385,  385,  386,  386,  387,  387,  388,
      388,  391,  391,  393,  393,  395,  395,  396,  396,  397,
      397,  398,  398,  399,  399,  400,  400,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[68] =
    {   0,
0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "patterns.l"
#line 2 "patterns.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	
	#include "y.tab.h"

	extern void yyerror(char *);
	void print_token(char *text, char *tokentext);
	
#line 876 "lex.yy.c"
#line 877 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 26 "patterns.l"


#line 29 "patterns.l"
	/*	Headers and Libraries	*/
#line 1099 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 366 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1168 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "patterns.l"
{;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 31 "patterns.l"
{;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 32 "patterns.l"
{
					/*printf("%s\n", yytext);*/
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "patterns.l"
{
					/*printf("%s\n", yytext);*/
				}
	YY_BREAK
/* Constants	*/
case 5:
YY_RULE_SETUP
#line 41 "patterns.l"
{ print_token(yytext, "T_CONSTANT");return(T_CONSTANT); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "patterns.l"
{ print_token(yytext, "T_CONSTANT"); return(T_CONSTANT); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 43 "patterns.l"
{ print_token(yytext, "T_CONSTANT"); return(T_CONSTANT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "patterns.l"
{ print_token(yytext, "T_CONSTANT"); return(T_CONSTANT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "patterns.l"
{ print_token(yytext, "T_CONSTANT"); return(T_CONSTANT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "patterns.l"
{ print_token(yytext, "T_CONSTANT"); return(T_CONSTANT); }
	YY_BREAK
/* String Literal	*/
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 50 "patterns.l"
{ print_token(yytext, "T_STRING_LITERAL"); return(T_STRING_LITERAL); }
	YY_BREAK
/* Language Constructs	*/
case 12:
YY_RULE_SETUP
#line 54 "patterns.l"
{ print_token(yytext, "T_CLASS"); return(T_CLASS); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "patterns.l"
{ print_token(yytext, "T_PUBLIC"); return (T_PUBLIC); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "patterns.l"
{ print_token(yytext, "T_PRIVATE"); return (T_PRIVATE); }
	YY_BREAK
/*"using"	{ print_token(yytext, "T_USING"); return (T_USING); }*/
/*"namespace"	{ print_token(yytext,""T_NAMESPACE"); return (T_NAMESPACE); }*/
/*"std"		{ print_token(yytext, "T_STD"); return (T_STD); }*/
/*"print"	{ print_token(yytext,"T_PRINT"); return (T_PRINT); }*/
/*"cout"	{ print_token(yytext, "T_COUT"); return (T_COUT); }*/
/*"endl"	{ print_token(yytext, "T_END"); return (T_ENDL); }*/
/*	Data Types	*/
case 15:
YY_RULE_SETUP
#line 66 "patterns.l"
{ print_token(yytext, "T_VOID"); return (T_VOID); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "patterns.l"
{ print_token(yytext, "T_CHAR"); return (T_CHAR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "patterns.l"
{ print_token(yytext, "T_INT"); return (T_INT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "patterns.l"
{ print_token(yytext, "T_FLOAT"); return (T_FLOAT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "patterns.l"
{ print_token(yytext, "T_DOUBLE"); return (T_DOUBLE); }
	YY_BREAK
/*	Control Structures */	
case 20:
YY_RULE_SETUP
#line 75 "patterns.l"
{ print_token(yytext, "T_IF"); return (T_IF); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "patterns.l"
{ print_token(yytext, "T_ELSE"); return (T_ELSE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 77 "patterns.l"
{ print_token(yytext, "T_WHILE"); return (T_WHILE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 78 "patterns.l"
{ print_token(yytext, "T_FOR"); return (T_FOR); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "patterns.l"
{ print_token(yytext, "T_SWITCH"); return (T_SWITCH); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "patterns.l"
{ print_token(yytext, "T_CASE"); return (T_CASE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "patterns.l"
{ print_token(yytext, "T_DEFAULT"); return (T_DEFAULT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "patterns.l"
{ print_token(yytext, "T_BREAK"); return (T_BREAK); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "patterns.l"
{ print_token(yytext, "T_CONTINUE"); return (T_CONTINUE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "patterns.l"
{ print_token(yytext, "T_RETURN"); return (T_RETURN); }
	YY_BREAK
/*	Relational Operators	*/
case 30:
YY_RULE_SETUP
#line 89 "patterns.l"
{ print_token(yytext, "T_LE_OP"); return (T_LE_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "patterns.l"
{ print_token(yytext, "T_GE_OP"); return (T_GE_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "patterns.l"
{ print_token(yytext, "T_EQ_OP"); return (T_EQ_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "patterns.l"
{ print_token(yytext, "T_NE_OP"); return (T_NE_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "patterns.l"
{ print_token(yytext, "<"); return ('<'); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "patterns.l"
{ print_token(yytext, ">"); return ('>');	}
	YY_BREAK
/*	Logical Operators	*/
case 36:
YY_RULE_SETUP
#line 97 "patterns.l"
{ print_token(yytext, "T_AND_OP"); return (T_AND_OP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "patterns.l"
{ print_token(yytext, "T_OR_OP"); return (T_OR_OP); }	
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "patterns.l"
{ print_token(yytext, "!"); return ('!'); }
	YY_BREAK
/*	Arithmetic Operators	*/
case 39:
YY_RULE_SETUP
#line 103 "patterns.l"
{ print_token(yytext, "T_INC_OP"); return (T_INC_OP); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "patterns.l"
{ print_token(yytext, "T_DEC_OP"); return (T_DEC_OP); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "patterns.l"
{ print_token(yytext, "+"); return ('+'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "patterns.l"
{ print_token(yytext, "-"); return ('-'); }	
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "patterns.l"
{ print_token(yytext, "*"); return ('*'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "patterns.l"
{ print_token(yytext, "/"); return ('/'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "patterns.l"
{ print_token(yytext, "%"); return ('%'); }
	YY_BREAK
/*	Synatx	*/
case 46:
YY_RULE_SETUP
#line 114 "patterns.l"
{ print_token(yytext, "="); return ('='); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 "patterns.l"
{ print_token(yytext, "T_PTR_OP"); return (T_PTR_OP); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 116 "patterns.l"
{ print_token(yytext, "["); return ('['); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 117 "patterns.l"
{ print_token(yytext, "]"); return (']'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 "patterns.l"
{ print_token(yytext, "."); return ('.'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "patterns.l"
{ print_token(yytext, ";"); return (';'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "patterns.l"
{ print_token(yytext, ","); return (','); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "patterns.l"
{ print_token(yytext, ":"); return (':'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "patterns.l"
{ print_token(yytext, "{"); return ('{'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "patterns.l"
{ print_token(yytext, "}"); return ('}'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "patterns.l"
{ print_token(yytext, "("); return ('('); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "patterns.l"
{ print_token(yytext, ")"); return (')'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "patterns.l"
{ print_token(yytext, "&"); return('&'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 128 "patterns.l"
{ print_token(yytext, "~"); return('~'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "patterns.l"
{ print_token(yytext, "^"); return('^'); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "patterns.l"
{ print_token(yytext, "|"); return('|'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 131 "patterns.l"
{ print_token(yytext, "?"); return('?'); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "patterns.l"
{ print_token(yytext, "T_IDENTIFIER"); return(T_IDENTIFIER); }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 135 "patterns.l"
{ print_token(yytext, "whitespace"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "patterns.l"
{ print_token(yytext, "whitespace"); }
	YY_BREAK
/*	Other	*/
case 66:
YY_RULE_SETUP
#line 139 "patterns.l"
{  }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "patterns.l"
ECHO;
	YY_BREAK
#line 1526 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 366 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 366 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 365);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "patterns.l"


void print_token(char *text, char *token_text)
{
	printf("%s\t\t%s\n", text, token_text);
}

int yywrap(void)
{
	return 1;
}

